import pandas_ta_classic as ta

def generate_signals(df, balance=10000):
    """Core logic with Phase 1 Realism Layer"""
    # 1. Indicator Setup (Ensures column names are standard)
    df.ta.rsi(length=14, append=True)
    df.ta.macd(append=True)
    df.ta.aroon(length=14, append=True)
    df.ta.atr(length=14, append=True)
    
    # 2. Get the last row
    last = df.iloc[-1]
    prev = df.iloc[-2]
    
    # 3. Extract Values (Using column names generated by pandas-ta)
    close = last['close']
    rsi = last['RSI_14']
    
    # MACD logic
    macd_line = last['MACD_12_26_9']
    macd_sig = last['MACDs_12_26_9']
    prev_macd_line = prev['MACD_12_26_9']
    prev_macd_sig = prev['MACDs_12_26_9']
    
    # Aroon & ATR (Handle the specific naming convention of pandas-ta)
    aroon_osc = last['AROONOSC_14']
    atr = last['ATRr_14']

    # 4. Strategy Logic: Triple Convergence
    verdict = "NEUTRAL"
    # LONG: RSI Oversold + MACD Bullish Cross + Aroon Strength
    if rsi < 35 and (macd_line > macd_sig and prev_macd_line <= prev_macd_sig) and aroon_osc > 0:
        verdict = "BUY / LONG"
    # SHORT: RSI Overbought + MACD Bearish Cross + Aroon Weakness
    elif rsi > 65 and (macd_line < macd_sig and prev_macd_line >= prev_macd_sig) and aroon_osc < 0:
        verdict = "SELL / SHORT"

    # 5. Realism & Sizing
    if verdict != "NEUTRAL":
        sl_dist = atr * 2
        # Risk 1% of balance
        units = (balance * 0.01) / sl_dist if sl_dist != 0 else 0
        est_fee = (units * close * 0.001) * 2 
        diag = f"RSI: {rsi:.1f} | Units: {units:.4f} | Est. Fee: ${est_fee:.2f}"
    else:
        diag = f"RSI: {rsi:.1f} | MACD: {'🟢' if macd_line > macd_sig else '🔴'}"

    return {"verdict": verdict, "price": close, "diag": diag}
